version: '2.3'

services:

  onbank_container:
    image: onbank_image
    container_name: onbank_container
    working_dir: /code
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PYTHONPATH=/code
    volumes:
      - ../:/code
      - /dev/video0:/dev/video0

    privileged: true
    command: tail /dev/null -f